import { VERIFICATION_STATUSES } from "@domain/enums/verificationStatus";

export type VERIFICATION_STATUS =
  | VERIFICATION_STATUSES.NOT_SUBMITTED
  | VERIFICATION_STATUSES.PENDING
  | VERIFICATION_STATUSES.APPROVED
  | VERIFICATION_STATUSES.REJECTED;
