export { default as AddDestinationForm } from "./AddDestinationForm";
export { default as SectionCard } from "./SectionCard";
export { default as BasicInfoSection } from "./BasicInfoSection";
export { default as ImageGallerySection } from "./ImageGallerySection";
export { default as LocationMapSection } from "./LocationMapSection";
export { default as DetailsClassificationSection } from "./DetailsClassificationSection";
export { default as VisitingHoursSection } from "./VisitingHoursSection";
export { default as AccessibilitySection } from "./AccessibilitySection";
export { default as EntryFeeSection } from "./EntryFeeSection";
