import {
    Footprints,
    Wind,
    Waves,
    Tent,
    Mountain,
    Sailboat,
    Ship,
    Bike,
    Snowflake,
    Cloud,
    Gem,
    Zap,
    Plane,
    Cable,
    Squirrel,
    Bird,
    User,
    Fish,
    Anchor,
    Rocket,
    Sun,
    Camera,
    Theater,
    Utensils,
    Moon,
    Heart,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";
import { ACTIVITY_TYPE } from "@/constants/destinationConstants/activityType";

export const activityTypeIcons: Record<ACTIVITY_TYPE, LucideIcon> = {
    [ACTIVITY_TYPE.HIKING]: Footprints,
    [ACTIVITY_TYPE.PARAGLIDING]: Wind,
    [ACTIVITY_TYPE.SCUBA_DIVING]: Waves,
    [ACTIVITY_TYPE.SNORKELING]: Waves,
    [ACTIVITY_TYPE.CAMPING]: Tent,
    [ACTIVITY_TYPE.TREKKING]: Mountain,
    [ACTIVITY_TYPE.RAFTING]: Sailboat,
    [ACTIVITY_TYPE.KAYAKING]: Ship,
    [ACTIVITY_TYPE.SURFING]: Waves,
    [ACTIVITY_TYPE.SKIING]: Snowflake,
    [ACTIVITY_TYPE.SNOWBOARDING]: Cloud,
    [ACTIVITY_TYPE.ROCK_CLIMBING]: Gem,
    [ACTIVITY_TYPE.BUNGEE_JUMPING]: Zap,
    [ACTIVITY_TYPE.SKYDIVING]: Plane,
    [ACTIVITY_TYPE.ZIP_LINING]: Cable,
    [ACTIVITY_TYPE.WILDLIFE_SAFARI]: Squirrel,
    [ACTIVITY_TYPE.BIRD_WATCHING]: Bird,
    [ACTIVITY_TYPE.CYCLING]: Bike,
    [ACTIVITY_TYPE.HORSEBACK_RIDING]: User,
    [ACTIVITY_TYPE.FISHING]: Fish,
    [ACTIVITY_TYPE.BOATING]: Anchor,
    [ACTIVITY_TYPE.JET_SKIING]: Rocket,
    [ACTIVITY_TYPE.HOT_AIR_BALLOONING]: Sun,
    [ACTIVITY_TYPE.SIGHTSEEING]: Camera,
    [ACTIVITY_TYPE.PHOTOGRAPHY]: Camera,
    [ACTIVITY_TYPE.CULTURAL_TOUR]: Theater,
    [ACTIVITY_TYPE.FOOD_TOUR]: Utensils,
    [ACTIVITY_TYPE.NIGHT_LIFE]: Moon,
    [ACTIVITY_TYPE.SPA_WELLNESS]: Heart,
};
