import {
    Palmtree,
    Mountain,
    Building2,
    Landmark,
    TreePine,
    Sun,
    Waves,
    Fish,
    Droplets,
    Squirrel,
    Castle,
    Church,
    Compass,
    MountainSnow,
    Home,
    Ship,
    Skull,
    MapPin,
    Snowflake,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { DESTINATION_TYPES } from "@/constants/destinationConstants/destinationType";

export const destinationTypeIcons: Record<DESTINATION_TYPES, LucideIcon> = {
    [DESTINATION_TYPES.BEACH]: Palmtree,
    [DESTINATION_TYPES.MOUNTAIN]: Mountain,
    [DESTINATION_TYPES.URBAN]: Building2,
    [DESTINATION_TYPES.MONUMENT]: Landmark,
    [DESTINATION_TYPES.FOREST]: TreePine,
    [DESTINATION_TYPES.DESERT]: Sun,
    [DESTINATION_TYPES.ISLAND]: Waves,
    [DESTINATION_TYPES.LAKE]: Fish,
    [DESTINATION_TYPES.WATERFALL]: Droplets,
    [DESTINATION_TYPES.WILDLIFE]: Squirrel,
    [DESTINATION_TYPES.HERITAGE]: Castle,
    [DESTINATION_TYPES.RELIGIOUS]: Church,
    [DESTINATION_TYPES.ADVENTURE]: Compass,
    [DESTINATION_TYPES.HILL_STATION]: MountainSnow,
    [DESTINATION_TYPES.COUNTRYSIDE]: Home,
    [DESTINATION_TYPES.COASTAL]: Ship,
    [DESTINATION_TYPES.CAVE]: Skull,
    [DESTINATION_TYPES.VALLEY]: MapPin,
    [DESTINATION_TYPES.GLACIER]: Snowflake,
};
