export enum CURRENCY {
  INR = "INR",
  USD = "USD",
  EUR = "EUR",
  GBP = "GBP",
  AUD = "AUD",
  CAD = "CAD",
  JPY = "JPY",
  CNY = "CNY",
  CHF = "CHF",
  SGD = "SGD",
  AED = "AED",
  SAR = "SAR",
  THB = "THB",
  MYR = "MYR",
  IDR = "IDR",
  PHP = "PHP",
  VND = "VND",
  KRW = "KRW",
  NZD = "NZD",
  ZAR = "ZAR",
  BRL = "BRL",
  MXN = "MXN",
  RUB = "RUB",
  TRY = "TRY",
  HKD = "HKD",
}
