export enum TRANSACTION_TYPE {
  COMMISSION = "COMMISSION",
  SERVICE_CREDIT = "SERVICE_CREDIT",
  PAYMENT = "PAYMENT",
  REFUND = "REFUND",
  TOP_UP = "TOP_UP",
  WALLET_DEBIT = "WALLET_DEBIT",
  WALLET_CREDIT = "WALLET_CREDIT",
  COMMISSION_DEBIT = "COMMISSION_DEBIT",
}
