import { AuthController } from "presentation/controllers/auth/authController";
import { container } from "tsyringe";
import { registerDI } from "@infrastructure/DI/register";
import { AuthMiddleware } from "presentation/middlewares/authMiddleware";
import { AdminController } from "presentation/controllers/admin/adminController";
import { CabController } from "@presentation/controllers/cab/cabController";
import { HotelController } from "@presentation/controllers/hotel/hotelController";
import { RoomVariantController } from "@presentation/controllers/roomVariant/roomVariantController";
import { DestinationController } from "@presentation/controllers/destination/destinationCotroller";
import { RoomController } from "@presentation/controllers/room/roomController";
import { PaymentController } from "@presentation/controllers/payment/paymentController";
import { WebHookController } from "@presentation/controllers/webhook/webhookController";

registerDI();
export const authController = container.resolve(AuthController);
export const adminController = container.resolve(AdminController);
export const authMiddleware = container.resolve(AuthMiddleware);
export const cabController = container.resolve(CabController);
export const destinationController = container.resolve(DestinationController);
export const hotelController = container.resolve(HotelController);
export const roomVariantController = container.resolve(RoomVariantController);
export const roomController = container.resolve(RoomController);
export const paymentController = container.resolve(PaymentController);
export const webhookController = container.resolve(WebHookController);
