export enum QUERY_KEYS {
    USERS = "USERS",
    USER_PROFILE = "USER_PROFILE ",
    UNVERIFIED_USERS = "UNVERIFIED_USERS",
    CAB_DETAILS = "CAB_DETAILS",
    DESTINATIONS = "DESTINATIONS",
    HOTEL = "HOTEL",
    ROOM_VARIANT = "ROOM_VARIANT",
    HOTEL_SEARCH = "HOTEL_SEARCH",
    ROOM_VARIANT_AVAILABILITY = "ROOM_VARIANT_AVAILABILITY",
    BOOKING = "BOOKING",
}
