export enum AuthRoutes {
  REGISTER = "/register",
  VERIFY = "/verify",
  RESEND_OTP = "/resend-otp",
  LOGIN = "/login",
  FORGET_PASSWORD = "/forget-password",
  FORGET_PASSWORD_VERIFY_OTP = "/forget-password-verify",
  FORGET_PASSWORD_RESET = "/forget-password-reset",
  REFRESH = "/refresh-token",
  LOGOUT = "/logout",
  GOOGLE_LOGIN = "/google-login",
  PROFILE = "/profile",
  CHANGE_PASSWORD = "/change-password",
  CHANGE_EMAIL_REQUEST_OTP = "/change-email-request-otp",
  CHANGE_EMAIL_VERIFY_OTP = "/change-email-verify-otp",
  CHANGE_EMAIL_NEW_EMAIL = "/change-email-new-email",
}
