export enum Routes {
  AUTH = "/api/v1/auth",
  ADMIN = "/api/v1/admin",
  CAB = "/api/v1/cab",
  HOTEL = "/api/v1/hotels",
  DESTINATION = "/api/v1/destinations",
  ROOM_VARIANT = "/api/v1/room-variants",
  ROOM = "/api/v1/rooms",
  PAYMENT = "/api/v1/payment",
  BOOKING = "/api/v1/bookings",
  WEBHOOK = "/api/v1/webhooks",
  RIDE = "/api/v1/ride",
  NOTIFICATION = "/api/v1/notifications",
  MONITORING = "/api/v1/monitoring",
  WALLET = "/api/v1/wallet",
  CAB_REVIEW = "/api/v1/cab-reviews",
  HOTEL_REVIEW = "/api/v1/hotel-reviews",
}
