export enum AUTH_ROUTES {
    SIGNUP = "/auth/register",
    VERIFY_OTP = "/auth/verify",
    RESEND_OTP = "/auth/resend-otp",
    LOGIN = "/auth/login",
    FORGET_SEND_OTP = "/auth/forget-password",
    FORGET_VERIFY_OTP = "/auth/forget-password-verify",
    FORGET_RESET_PASSWORD = "/auth/forget-password-reset",
    REFRESH = "/auth/refresh-token",
    LOGOUT = "/auth/logout",
    GOOGLE_LOGIN = "/auth/google-login",
    USER_PROFILE = "/auth/profile",
    CHANGE_PASSWORD = "/auth/change-password",
    CHANGE_EMAIL_REQUEST_OTP = "/auth/change-email-request-otp",
    CHANGE_EMAIL_VERIFY_OTP = "/auth/change-email-verify-otp",
    CHANGE_EMAIL_NEW_EMAIL = "/auth/change-email-new-email",
}
